name: Process survey's entry
on:
  issues:
    types: [ opened ]
concurrency: 'main'
jobs:
  take_survey:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: peter-murray/issue-forms-body-parser@v2.0.0
        id: issue-parser
        with:
          issue_id: ${{ github.event.issue.number }}
          label_marker_start: '>>'
          label_marker_end: '<<'

      - run: echo echo "${{ steps.parse.outputs.payload }}" > survey.json

      - run: cat survey.json

#       - run: node ./place-order.js
#
#       - name: Commit changes
#         shell: bash
#         run: |
#           git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
#           git config --global user.name "github-actions[bot]" && \
#           git add README.md && \
#           git commit -m 'Place order' && \
#           git push
#
#       - uses: peter-evans/close-issue@v1
#         with:
#           comment: Pizza time! Check out the <a href="../">README</a>.
